name: Lint pull request title

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: write
  pull-requests: write
  statuses: write

## Pattern to match strings as follows:
# feat(ui): add `Button` component
# ^    ^    ^
# |    |    |__ Subject
# |    |_______ Scope
# |____________ Type

jobs:
  main:
    runs-on: ubuntu-latest
    name: lint PR title
    steps:
      # Skip PR title lint in case of a `merge_group` event as the lint
      - name: Skip if "merge_group" event
        if: github.event_name == 'merge_group'
        shell: bash
        run: |
          echo "Skipping because the event is a 'merge_group'."

      - name: Validate PR title
        if: github.event_name != 'merge_group'
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: '.+[A-Z]+-[0-9]+.*'

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fail, the workflow would stop. By adding this
        # condition we can continue the execution with the populated error message.
        if: (github.event_name != 'merge_group') && always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to be formatted as follows:
            ```
            feat(ui): add `Button` component
            ^    ^    ^
            |    |    |__ Subject
            |    |_______ Scope
            |____________ Type

            ```
            
            The subject should contain a reference to a JIRA ticket. Ex: CP-4340

            The current title does not match this format.
            <details>
              <summary>Error details 👀</summary>
            
              ```
              ${{ steps.lint_pr_title.outputs.error_message }}
              ```
            </details>

      # Delete a previous comment when the issue has been resolved
      - if: github.event_name != 'merge_group' && steps.lint_pr_title.outputs.error_message == null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true